# Generated by Django 4.0.4 on 2022-05-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('grade', models.IntegerField()),
                ('salary', models.FloatField()),
                ('dateOfJoining', models.DateField()),
            ],
        ),
    ]
