# Generated by Django 4.0.4 on 2022-05-17 06:02

import concurrency.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_empno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='version',
            field=concurrency.fields.IntegerVersionField(default=0, help_text='record revision number'),
        ),
    ]
